-- RUN THIS IN SUPABASE SQL EDITOR

CREATE TABLE IF NOT EXISTS incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id TEXT NOT NULL,
  user_tag TEXT,
  title TEXT NOT NULL,
  description TEXT,
  severity TEXT CHECK (severity IN ('BAJA', 'MEDIA', 'ALTA', 'CRITICA')),
  status TEXT DEFAULT 'ABIERTO',
  thread_id TEXT
);

-- Policy to allow Bot (service_role) to do everything
-- (If you have RLS enabled, ensure service_role has access by default, which it usually does)
